name: dart_naver_papago
description: A unofficial package for using Naver Papago translation, language detection, romanization api.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  http: ^0.13.5
  json_annotation: ^4.8.0
  plugin_platform_interface: ^2.0.2
  dart_naver_without_login_common:
    path: ../dart_naver_without_login_common
dev_dependencies:
  json_serializable: ^6.6.1
  build_runner: ^2.3.3
  lints: ^2.0.0
  test: ^1.21.0
