name: dart_naver_without_login_common
description: A unofficial package contains common features for Naver apis that do not require login in Dart language.
version: 0.0.1
repository: https://github.com/Coaspe/dart_naver_without_login

environment:
  sdk: '>=2.19.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
dependencies:
  http: ^0.13.5