name: dart_naver_clova_face_recognition
description: An unofficial package for using Naver Clova face recognition, celebrity recognition.
version: 0.0.1
repository: https://github.com/Coaspe/dart_naver_clova_face_recognition

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  http: ^0.13.5
  json_annotation: ^4.8.0
  plugin_platform_interface: ^2.0.2
  dart_naver_without_login_common: ^0.0.3
dev_dependencies:
  json_serializable: ^6.6.1
  build_runner: ^2.3.3
  lints: ^2.0.0
  test: ^1.21.0
