import 'enums.dart';

const papagoTranslationLanguages = <LangCode>{
  LangCode.ko,
  LangCode.en,
  LangCode.ja,
  LangCode.zhCN,
  LangCode.zhTW,
  LangCode.vi,
  LangCode.th,
  LangCode.id,
  LangCode.fr,
  LangCode.es,
  LangCode.ru,
  LangCode.de,
  LangCode.it,
};

const Map<LangCode, Set<LangCode>> possibleSrcToTar = {
  LangCode.auto: papagoTranslationLanguages,
  LangCode.ko: {
    LangCode.en,
    LangCode.ja,
    LangCode.zhCN,
    LangCode.zhTW,
    LangCode.vi,
    LangCode.th,
    LangCode.id,
    LangCode.fr,
    LangCode.es,
    LangCode.ru,
    LangCode.de,
    LangCode.it,
  },
  LangCode.en: {
    LangCode.ko,
    LangCode.ja,
    LangCode.zhCN,
    LangCode.zhTW,
    LangCode.vi,
    LangCode.th,
    LangCode.id,
    LangCode.fr,
    LangCode.es,
    LangCode.ru,
    LangCode.de,
  },
  LangCode.ja: {
    LangCode.ko,
    LangCode.en,
    LangCode.zhCN,
    LangCode.zhTW,
    LangCode.vi,
    LangCode.th,
    LangCode.id,
    LangCode.fr,
  },
  LangCode.zhCN: {LangCode.ko, LangCode.en, LangCode.ja, LangCode.zhTW},
  LangCode.zhTW: {LangCode.ko, LangCode.en, LangCode.ja, LangCode.zhCN},
  LangCode.vi: {LangCode.ko, LangCode.en, LangCode.ja},
  LangCode.th: {LangCode.ko, LangCode.en, LangCode.ja},
  LangCode.id: {LangCode.ko, LangCode.en, LangCode.ja},
  LangCode.fr: {LangCode.ko, LangCode.en, LangCode.ja},
  LangCode.es: {LangCode.ko, LangCode.en},
  LangCode.ru: {LangCode.ko, LangCode.en},
  LangCode.de: {LangCode.ko, LangCode.en},
  LangCode.it: {LangCode.ko},
};
